services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/code/app/src
    depends_on:
      - db
  db:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
